### PR TITLE
chore: Add @maddhruv and @ryzokuken to members list.

### PR DESCRIPTION
**Pull request by amiller-gh**
Addresses: https://github.com/nodejs/badges/issues/11

### CODE REVIEW

**Comment by amiller-gh** [comment]
@ryzokuken, been enjoying your engagement with this initiative as well, would you like to be added as a team member too?

**Comment by ryzokuken** [comment]
@amiller-gh nothing could be better. Thanks.

**Review by Tiriel — APPROVED** [review]

**Comment by amiller-gh** [comment]
Welcome to the team @ryzokuken and @maddhruv! 🎉

**Comment by maddhruv** [comment]
Thanks @amiller-gh
Excited to be in _badge_ and hope to get some cool things out

**Pull request merged**
